access/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  scope "(:locale)", locale: /#{APP_CONFIG['available_locales'].join('|')}/ do
    root 'site#index'
    get '/:locale' => 'people#index'
    resources :people do
      get 'versions' => 'people_versions#index'
    end
    get '/people/confirm_email/:token' => 'people#verify_email', as: 'verify_email'

    resources :organizations
    resources :hosts do
      get 'versions' => 'hosts_versions#index'
    end
    resources :certificate_requests, except: [:edit] do
      post 'approve' => 'certificate_requests#approve_csr', as: 'approve'
      post 'reject' => 'certificate_requests#reject_csr', as: 'reject'
    end

    get '/:user_id/csr' => 'certificate_requests#mozilla_csr', as: 'mozilla_csr'
    post '/:user_id/submit' => 'certificate_requests#csr_submission', as: 'csr_submission'
    get '/error_csr_sub' => 'certificate_requests#error_csr_sub', as: 'csr_error'
    get '/find_csr' => 'certificate_requests#find_csr', as: 'find_csr'
    post '/find_csr' => 'certificate_requests#csr_value'
    get '/find_csr/no_csr' => 'certificate_requests#error', as: 'no_csr'

    get '/ra/csr_list' => 'ra#csr_list'
    get '/ra/csr_pending' => 'ra#csr_pending'
    get '/ra/csr_approved' => 'ra#csr_approved'
    get '/ra/csr_rejected' => 'ra#csr_rejected'

    get 'ca/list_approved' => 'ca#list_approved'
    get 'ca/upload_certs' => 'ca#upload_certs_file'
    post 'ca/upload_certs' => 'ca#upload_certs'

    get '/signup' => 'people#new', as: 'signup'
    get '/login' => 'sessions#new', as: 'login'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy', as: 'logout'

    mount Sidekiq::Web => '/sidekiq'
  end

end

access/app/models/host.rb
class Host < ActiveRecord::Base
  # Associations
  belongs_to :person
  belongs_to :organization
  has_many :distinguished_names, as: :owner
  has_many :alternative_hostnames

  # Validations
  validates :person, presence: true
  validates :organization, presence: true
  validates :fqdn, presence: true, hostname: true, institutional_hostname: true

  # Versioning
  has_paper_trail
end

access/app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_action :set_host, only: [:show, :edit, :update, :destroy]
  before_filter :authorize!

  # GET /hosts
  # GET /hosts.json
  def index
    @hosts = Host.all
  end

  # GET /hosts/1
  # GET /hosts/1.json
  def show
  end

  # GET /hosts/new
  def new
    @host = Host.new
  end

  # GET /hosts/1/edit
  def edit
  end

  # POST /hosts
  # POST /hosts.json
  def create
    @host = Host.new(host_params)
    @host.person = current_user

    respond_to do |format|
      if @host.save
        format.html { redirect_to @host, notice: 'Host was successfully created.' }
        format.json { render :show, status: :created, location: @host }
      else
        format.html { render :new }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hosts/1
  # PATCH/PUT /hosts/1.json
  def update
    respond_to do |format|
      if @host.update(host_params)
        format.html { redirect_to @host, notice: 'Host was successfully updated.' }
        format.json { render :show, status: :ok, location: @host }
      else
        format.html { render :edit }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1
  # DELETE /hosts/1.json
  def destroy
    @host.destroy
    respond_to do |format|
      format.html { redirect_to hosts_url, notice: 'Host was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_host
      @host = Host.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def host_params
      params.require(:host).permit(:fqdn, :person_id, :organization_id)
    end

    def authorize!
      super
      if @host && (@host.person != current_user) && (!TmpAdmin.is_admin?(current_user))
        redirect_to hosts_url, alert: "#{I18n.t 'controllers.authorization.not_authorized'}"
      end
    end
end

access/app/helpers/hosts_helper.rb
module HostsHelper
end

access/app/views/hosts/_form.html.erb
<%= form_for(@host) do |f| %>
  <% if @host.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@host.errors.count, "error") %> prohibited this host from being saved:</h2>

      <ul>
      <% @host.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :fqdn %><br>
      <%= f.text_field :fqdn %>
    </div>

    <div class="field">
      <%= f.label :organization %><br>
      <%= f.collection_select(:organization_id, Organization.all, :id, :name) %>
    </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

access/app/views/hosts/edit.html.erb
<h1>Editing Host</h1>

<%= render 'form' %>

<%= link_to 'Show', @host %> |
<%= link_to 'Back', hosts_path %>

access/app/views/hosts/index.html.erb
<h1>Listing Hosts</h1>

<table>
  <thead>
    <tr>
      <th>FQDN</th>
      <th><%= I18n.t "views.label.host.admin" %></th>
      <th><%= I18n.t "views.label.host.organization" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hosts.each do |host| %>
      <tr>
        <td><%= host.fqdn %></td>
        <td><%= host.person.email %></td>
        <td><%= host.organization.name %></td>
        <td><%= link_to 'Show', host %></td>
        <td><%= link_to 'Edit', edit_host_path(host) %></td>
        <td><%= link_to 'Destroy', host, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Host', new_host_path %>

access/app/views/hosts/new.html.erb
<h1>New Host</h1>

<%= render 'form' %>

<%= link_to 'Back', hosts_path %>

access/app/views/hosts/show.html.erb
<p>
  <strong>FQDN:</strong>
  <%= @host.fqdn %>
</p>

<p>
  <strong><%= I18n.t "views.label.host.admin" %>:</strong>
  <%= @host.person.email %>
</p>

<p>
  <strong><%= I18n.t "views.label.host.organization" %>:</strong>
    <%= @host.organization.name %>
</p>

<%= link_to 'Edit', edit_host_path(@host) %> |
<%= link_to 'Back', hosts_path %>