access/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  scope "(:locale)", locale: /#{APP_CONFIG['available_locales'].join('|')}/ do
    root 'site#index'
    get '/:locale' => 'people#index'
    resources :people do
      get 'versions' => 'people_versions#index'
    end
    get '/people/confirm_email/:token' => 'people#verify_email', as: 'verify_email'

    resources :organizations
    resources :hosts do
      get 'versions' => 'hosts_versions#index'
    end
    resources :certificate_requests, except: [:edit] do
      post 'approve' => 'certificate_requests#approve_csr', as: 'approve'
      post 'reject' => 'certificate_requests#reject_csr', as: 'reject'
    end

    get '/:user_id/csr' => 'certificate_requests#mozilla_csr', as: 'mozilla_csr'
    post '/:user_id/submit' => 'certificate_requests#csr_submission', as: 'csr_submission'
    get '/error_csr_sub' => 'certificate_requests#error_csr_sub', as: 'csr_error'
    get '/find_csr' => 'certificate_requests#find_csr', as: 'find_csr'
    post '/find_csr' => 'certificate_requests#csr_value'
    get '/find_csr/no_csr' => 'certificate_requests#error', as: 'no_csr'

    get '/ra/csr_list' => 'ra#csr_list'
    get '/ra/csr_pending' => 'ra#csr_pending'
    get '/ra/csr_approved' => 'ra#csr_approved'
    get '/ra/csr_rejected' => 'ra#csr_rejected'

    get 'ca/list_approved' => 'ca#list_approved'
    get 'ca/upload_certs' => 'ca#upload_certs_file'
    post 'ca/upload_certs' => 'ca#upload_certs'

    get '/signup' => 'people#new', as: 'signup'
    get '/login' => 'sessions#new', as: 'login'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy', as: 'logout'

    mount Sidekiq::Web => '/sidekiq'
  end

end

access/app/models/certificate_request.rb
require 'exceptions/invalid_action'
require 'json'

class CertificateRequest < ActiveRecord::Base
  # Associations
  belongs_to :requestor,
             class_name: 'Person',
             foreign_key: 'requestor_id'

  belongs_to :owner_dn,
             class_name: 'DistinguishedName',
             foreign_key: 'owner_dn_id'

  belongs_to :organization

  # Validations
  validates :status, presence: true, allow_nil: false
  validates_inclusion_of :status, in: %w(pending rejected signed approved)
  validates :body, presence: true
  validates :body, csr: true,
            unless: Proc.new {|obj| obj.body.nil?}
  validates :body, hostname_dn: true,
            if: Proc.new { |obj|
              if obj.owner_dn_id
                DistinguishedName.find(obj.owner_dn_id).owner_type == 'Host'
              else
                errors[:body] << "No dn provided to assess."
              end

                } # in case of error, this is difficult to debug
  validates :uuid, presence: true, uniqueness: true
  validates :csr_type, presence: true, allow_nil: false
  validates_inclusion_of :csr_type, in: %w(classic spkac classic_ie vista_ie)
  validates :requestor_id, presence: true
  validates :owner_dn_id, presence: true
  validates :owner_dn_id, uniqueness: true, if: Proc.new { |a| a.owner_dn.owner_type == 'Person' unless a.owner_dn.nil? }
  validates :organization_id, presence: true

  def self.approve_csr(csr_id)
    csr = CertificateRequest.find(csr_id)
    if csr.status == 'pending'
      csr.status = 'approved'
      csr.save!
    else
      raise InvalidActionError.new("#{I18n.t "exceptions.invalid_action.approve_csr"} #{csr.status}")
    end
  end

  def self.reject_csr(csr_id)
    csr = CertificateRequest.find(csr_id)
    if csr.status == 'pending'
      csr.status = 'rejected'
      csr.save!
    else
      raise InvalidActionError.new("#{I18n.t "exceptions.invalid_action.reject_csr"} #{csr.status}")
    end
  end

  def export_xml
    construct_request_hash.to_xml
  end

  def export_json
    construct_request_hash.to_json
  end

  def extract_alternative_names(show_order=false)
    dn = ""
    if self.csr_type == 'classic'
      dn = CertificateAuthority::SigningRequest.from_x509_csr(self.body).distinguished_name.x509_name.to_s
    elsif self.csr_type == 'spkac'
      dn = self.body.split("/SPKAC=")[0]
    end
    if (/subjectAltName/ =~ self.body)
      if show_order
        alt_names = dn.split('/subjectAltName=')[1].split(',')
      else
        alt_names = dn.split('/subjectAltName=')[1].split(Regexp.union([',', '='])).delete_if {|val| val=~ Regexp.union([/email\.\d+/, /DNS\.\d+/])}
      end

    else
      alt_names = []
    end
    alt_names
  end

  private
  def construct_request_hash
    request_hash = {}
    request_hash[:body] = self.body
    request_hash[:csr_type] = self.csr_type

    request_hash[:altnames] = extract_alternative_names(show_order: true)
    request_hash[:uniqueid] = self.uuid

    request_hash
  end
end

access/app/controllers/certificate_requests_controller.rb
require 'helpers/x509_helpers'

class CertificateRequestsController < ApplicationController
  before_action :set_certificate_request, only: [:show, :edit, :update, :destroy]
  before_filter :authorize!

  # GET /certificate_requests
  # GET /certificate_requests.json
  def index
    @certificate_requests = CertificateRequest.all
  end

  # GET /certificate_requests/1
  # GET /certificate_requests/1.json
  def show
  end

  # GET /certificate_requests/new
  def new
    @certificate_request = CertificateRequest.new
  end

  # GET /certificate_requests/1/edit
  def edit
  end

  # POST /certificate_requests
  # POST /certificate_requests.json
  def create
    @certificate_request = CertificateRequest.new(certificate_request_params)
    @certificate_request.requestor = current_user
    X509Helpers.csr_creation(@certificate_request, params, session)

    respond_to do |format|
      if @certificate_request.save
        format.html { redirect_to certificate_requests_url, notice: 'Certificate request was successfully created.' }
        format.json { render :show, status: :created, location: @certificate_request }
      else
        # The form only shows the CSR body, so all errors have to relate to this field.
        if (@certificate_request.errors['body'])
          @certificate_request.errors.each do |k,v|
            @certificate_request.errors.delete(k) unless k == :body
          end
        end
        format.html { render :new }
        format.json { render json: @certificate_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /certificate_requests/1
  # PATCH/PUT /certificate_requests/1.json
  def update
    respond_to do |format|
      if @certificate_request.update(certificate_request_params)
        format.html { redirect_to @certificate_request, notice: 'Certificate request was successfully updated.' }
        format.json { render :show, status: :ok, location: @certificate_request }
      else
        format.html { render :edit }
        format.json { render json: @certificate_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certificate_requests/1
  # DELETE /certificate_requests/1.json
  def destroy
    @certificate_request.destroy
    respond_to do |format|
      format.html { redirect_to certificate_requests_url, notice: 'Certificate request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def approve_csr
    begin
      CertificateRequest.approve_csr(params[:certificate_request_id])
    rescue InvalidActionError => e
      redirect_to certificate_requests_url, flash: { error: "#{e.message}" }
      return
    end
    redirect_to certificate_requests_url, notice: "Updated!"
  end

  def reject_csr
    begin
      CertificateRequest.reject_csr(params[:certificate_request_id])
    rescue InvalidActionError => e
      redirect_to certificate_requests_url, flash: { error: "#{e.message}" }
      return
    end
    redirect_to certificate_requests_url, notice: "Updated!"
  end

  #################### Mozilla Generated CSRs ####################
  ################################################################

  def mozilla_csr
    @country = APP_CONFIG['registration']['accept_csr_only_from_country']
    @person = Person.find(params[:user_id])
  end

  def csr_submission
    @csr = CertificateRequest.new(requestor_id: current_user.id)
    X509Helpers.csr_spkac_creation(@csr, params)

    if @csr.save
      render :inline => '<pre><%= @csr.body %></pre>'
    else
      redirect_to action: 'error_csr_sub'
    end

  end

  def error_csr_sub
  end

  def csr_value
    email = params[:emailAddress]
    @person = Person.find_by(:email => email)
    if @person
      id = @person.id
      @status = CertificateRequest.find_by(:id => id)
      if @status
        render :inline => '<pre><%= @status.status %></pre>'
      else
        redirect_to :action => "error"
      end
    else
      redirect_to :action => "error"
    end

  end

  def error
  end

  ################################################################

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certificate_request
      @certificate_request = CertificateRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def certificate_request_params
      params.require(:certificate_request).permit(:body)
    end

    def authorize!
      super
      if @certificate_request && (@certificate_request.requestor_id != current_user.id) && (!TmpAdmin.is_admin?(current_user))
        redirect_to certificate_requests_url, alert: "#{I18n.t 'controllers.authorization.not_authorized'}"
      end
    end
end

access/app/helpers/certificate_requests_helper.rb
module CertificateRequestsHelper
end

access/app/views/certificate_requests/_form.html.erb
<%= form_for(@certificate_request) do |f| %>
    <% if @certificate_request.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@certificate_request.errors.count, "error") %> prohibited this certificate_request from
            being saved:</h2>

          <ul>
            <% @certificate_request.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>


    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

access/app/views/certificate_requests/error.html.erb
<h1><%= I18n.t "views.error.error" %></h1>
<p><%= I18n.t "views.error.no_csr" %></p>
<p><%= I18n.t "views.error.no_reg" %>: <%= link_to "register here", new_person_path %> </p>

access/app/views/certificate_requests/error_csr_sub.html.erb
<h1><%= I18n.t "views.error.csr_gen" %></h1>
<p><%= I18n.t "views.error.already_csr" %>: <%= link_to "find your csr status", find_csr_url %></p>
<p><%= I18n.t "views.error.no_reg" %>: <%= link_to "register here", new_person_path %> </p>

access/app/views/certificate_requests/find_csr.html.erb
<%= form_tag 'find_csr' do %>
    <strong>E-mail:</strong>
    <input name="emailAddress" ><br />
    <input type="submit" value="Submit" class="textbox"><br /><br />
<%end%>

access/app/views/certificate_requests/index.html.erb
<h1><%= I18n.t('views.list_csr') %></h1>

<table>
  <thead>
    <tr>
      <th><%= I18n.t "views.label.certificate_request.uuid"%></th>
      <th><%= I18n.t "views.label.certificate_request.status"%></th>
      <th><%= I18n.t "views.label.certificate_request.owner"%></th>
      <th><%= I18n.t "views.label.certificate_request.organization"%></th>
      <th colspan="2"></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @certificate_requests.each do |certificate_request| %>
      <tr>
        <td><%= certificate_request.uuid %>></td>
        <td><%= certificate_request.status %>></td>
        <td><%= certificate_request.owner_dn.subject_dn %>></td>
        <td><%= certificate_request.organization.name %>></td>
        <td><%= link_to I18n.t("views.show"), certificate_request %></td>
        <td><%= link_to I18n.t("views.destroy"), certificate_request, method: :delete, data: { confirm: I18n.t("views.delete_confirmation") } %></td>
        <td><%= link_to I18n.t("views.accept"), certificate_request_approve_url(certificate_request), method: :post %></td>
        <td><%= link_to I18n.t("views.reject"), certificate_request_reject_url(certificate_request), method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to I18n.t('views.new_csr'), new_certificate_request_path %>

access/app/views/certificate_requests/mozilla_csr.html.erb
<%= form_tag 'submit' do %>
    <h2>E-mail:</h2>
    <input name="emailAddress" value="<%= @person.email %>" readonly><br />

    <h2>Common Νame(CN)</h2>
    <% person_cn = @person.first_name_latin.capitalize + " " + @person.last_name_latin.capitalize %>
    <input name="commonName" value="<%=[@person.first_name_latin.capitalize, @person.last_name_latin.capitalize].join(' ') %>" readonly><br />

    <h2>Organization Name(O)</h2>
    <%if @organization%>
      <input name="organizationName" value="<%= @organization %>" readonly><br />
    <% else %>
      <input name="organizationName" value=""><br />
    <% end %>
    
    <h2>Organizational Unit Name(OU)</h2>
    <input name="organizationalUnitName" value="<%= @person.organization.domain %>" readonly><br />
    
    <h2>Country Name(C)</h2>
    <%if @country%>
      <input name="countryName" value="<%=@country%>" readonly><br />
    <%else%>
      <input name="countryName" value=""><br />
    <% end %>
    <label for="SPKAC"><h2>Key_size:</h2></label><br />
    <keygen name="SPKAC" class="textbox" keytype="rsa"></keygen><br />
    <input type="submit" value="<%="#{I18n.t "views.submit"}"%>" class="textbox"><br /><br />
<%end%>

access/app/views/certificate_requests/new.html.erb
<h1><%= I18n.t('views.new_csr') %></h1>

<%= render 'form' %>

<%= link_to I18n.t('views.back'), certificate_requests_path %>

access/app/views/certificate_requests/show.html.erb
<p>
  <strong><%= I18n.t "views.label.certificate_request.uuid" %>:</strong>
  <%= @certificate_request.uuid %>
</p>

<p>
  <strong><%= I18n.t "views.label.certificate_request.body" %>:</strong>
  <%= @certificate_request.body %>
</p>

<p>
  <strong><%= I18n.t "views.label.certificate_request.requestor" %>:</strong>
  <%= @certificate_request.requestor %>
</p>

<p>
  <strong><%= I18n.t "views.label.certificate_request.owner" %>:</strong>
  <%= @certificate_request.owner_dn.subject_dn %>
</p>

<p>
  <strong><%= I18n.t "views.label.certificate_request.organization" %>:</strong>
  <%= @certificate_request.organization.name %>
</p>

<p>
  <strong><%= I18n.t "views.label.certificate_request.status" %>:</strong>
  <%= @certificate_request.status %>
</p>

<%= link_to 'Back', certificate_requests_path %>