access/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  scope "(:locale)", locale: /#{APP_CONFIG['available_locales'].join('|')}/ do
    root 'site#index'
    get '/:locale' => 'people#index'
    resources :people do
      get 'versions' => 'people_versions#index'
    end
    get '/people/confirm_email/:token' => 'people#verify_email', as: 'verify_email'

    resources :organizations
    resources :hosts do
      get 'versions' => 'hosts_versions#index'
    end
    resources :certificate_requests, except: [:edit] do
      post 'approve' => 'certificate_requests#approve_csr', as: 'approve'
      post 'reject' => 'certificate_requests#reject_csr', as: 'reject'
    end

    get '/:user_id/csr' => 'certificate_requests#mozilla_csr', as: 'mozilla_csr'
    post '/:user_id/submit' => 'certificate_requests#csr_submission', as: 'csr_submission'
    get '/error_csr_sub' => 'certificate_requests#error_csr_sub', as: 'csr_error'
    get '/find_csr' => 'certificate_requests#find_csr', as: 'find_csr'
    post '/find_csr' => 'certificate_requests#csr_value'
    get '/find_csr/no_csr' => 'certificate_requests#error', as: 'no_csr'

    get '/ra/csr_list' => 'ra#csr_list'
    get '/ra/csr_pending' => 'ra#csr_pending'
    get '/ra/csr_approved' => 'ra#csr_approved'
    get '/ra/csr_rejected' => 'ra#csr_rejected'

    get 'ca/list_approved' => 'ca#list_approved'
    get 'ca/upload_certs' => 'ca#upload_certs_file'
    post 'ca/upload_certs' => 'ca#upload_certs'

    get '/signup' => 'people#new', as: 'signup'
    get '/login' => 'sessions#new', as: 'login'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy', as: 'logout'

    mount Sidekiq::Web => '/sidekiq'
  end

end

access/app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :people

  validates :domain, uniqueness: { case_sensitive: false }, presence: true
  validates :name, presence: true

  translates :name, :description
end

access/app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  before_filter :authorize!

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
    @locales = APP_CONFIG['available_locales'].map { |locale| locale.to_sym }
    @locales -= [params[:locale].to_sym]
  end

  # GET /organizations/1/edit
  def edit
    @locales = APP_CONFIG['available_locales'].map { |locale| locale.to_sym }
    @locales -= [params[:locale].to_sym]
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)
    edit_other_locales_params
    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit_other_locales_params
    @locales = APP_CONFIG['available_locales'].map { |locale| locale.to_sym }
    @locales -= [params[:locale].to_sym]
    org_locales_params = {}
    @locales.each do |locale|
      org_locales_params[locale.to_sym] = {name: nil, description: nil}
      org_locales_params[locale.to_sym][:name] = params["name_#{locale}"] if params["name_#{locale}"]
      org_locales_params[locale.to_sym][:description] = params["description_#{locale}"] if params["description_#{locale}"]
    end

    org_locales_params.each do |locale, hash|
      Globalize.with_locale(locale) do
        @organization.name = hash[:name] if hash[:name]
        @organization.description = hash[:description] if hash[:description]
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    edit_other_locales_params
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :domain, :description)
    end

    def authorize!
      super
      redirect_to root_url, alert: "#{I18n.t 'controllers.authorization.not_authorized'}" unless TmpAdmin.is_admin?(current_user)
    end
end

access/app/helpers/organizations_helper.rb
module OrganizationsHelper
end

access/app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
    <% if @organization.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

          <ul>
            <% @organization.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :domain %><br>
      <%= f.text_field :domain %>
    </div>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>

    <div class="other_locales">
      <h3><%= "#{I18n.t "views.organizations.other_locales"}" %></h3>
      <table>
        <thead>
          <td>Locale</td>
          <td><%= f.label :name %></td>
          <td><%= f.label :description %></td>
        </thead>
      <%@locales.each do |locale|%>
            <% Globalize.with_locale(locale) do %>
              <tr>
                <td><%= "#{locale}" %></td>
                <td><%= text_field_tag("name_#{locale}", @organization.name) %></td>
                <td><%= text_area_tag("description_#{locale}", @organization.description)%></td>
              </tr>
            <% end %>
      <% end %>
      </table>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

access/app/views/organizations/edit.html.erb
<h1><%=I18n.t "views.edit_organization"%></h1>

<%= render 'form' %>

<%= link_to "#{I18n.t "views.show"}", @organization %> |
<%= link_to "#{I18n.t "views.back"}", organizations_path %>

access/app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= I18n.t('views.list_organizations') %></h1>

<table>
  <thead>
    <tr>
      <th><%= I18n.t "views.label.organization.name" %></th>
      <th><%= I18n.t "views.label.organization.domain" %></th>
      <th><%= I18n.t "views.label.organization.description" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.domain %></td>
        <td><%= organization.description %></td>
        <td><%= link_to I18n.t("views.show"), organization %></td>
        <td><%= link_to I18n.t("views.edit"), edit_organization_path(organization) %></td>
        <td><%= link_to I18n.t("views.destroy"), organization, method: :delete, data: { confirm: I18n.t("views.delete_confirmation") } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to I18n.t('views.new_organization'), new_organization_path %>

access/app/views/organizations/new.html.erb
<h1><%= I18n.t "views.new_organization"%></h1>

<%= render 'form' %>

<%= link_to "#{I18n.t "views.back"}", organizations_path %>

access/app/views/organizations/show.html.erb
<p>
  <strong><%= I18n.t "views.label.organization.name" %>:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong><%= I18n.t "views.label.organization.domain" %>:</strong>
  <%= @organization.domain %>
</p>

<p>
  <strong><%= I18n.t "views.label.organization.description" %>:</strong>
  <%= @organization.description %>
</p>

<%= link_to I18n.t('views.edit'), edit_organization_path(@organization) %> |
<%= link_to I18n.t('views.back'), organizations_path %>